### ISSUE TITLE
parse  job

### ISSUE THREAD

**Issue by haichaoshi** [gideonairex/disqueue-node#15]
How to parse body of the job （getJob  API），now，it is  ‘[object,object]’

**Comment by gideonairex** [comment]
I think what you have done is placed the object on the body on adding a job. With that if you get the job it will give you an object string. The way to handle this is to use JSON.stringify the object first. Then after that JSON.parse the result.

**Comment by haichaoshi** [comment]
Is my mistake,I sent in an object parameter(addJob API),sorry!
