### ISSUE TITLE
Emit error event when failed to connect

### ISSUE THREAD

**Issue by swarajban** [gideonairex/disqueue-node#4]
When instantiating a new Disqueue, and disqueue cannot be reached, the client does not emit the `error` event

**Comment by gideonairex** [comment]
This is existing. How did you listen for the error? Can I see your code.
Heres and [example](https://github.com/gideonairex/disqueue-node/blob/master/example/server.js#L11)

**Comment by swarajban** [comment]
My code is below, I'm running node v4.2.4. The `'error'` event is never emitted when my `DISQUE_SERVICE_HOST` environment variable points to a non-existent host. I am currently 'getting around' this by by just setting a timeout.

```
const disqueueOptions = {
  host: process.env.DISQUE_SERVICE_HOST,
  port: process.env.DISQUE_SERVICE_PORT
};

export let disqueueClient = null;

export function initDisqueue () {
  disqueueClient = new Disqueue(disqueueOptions);
  let connected = false;
  disqueueClient.on('connected', () => {
    logger.info('Connected to disque!');
    connected = true;
  });

  disqueueClient.on('error', (err) => {
    logger.error(`Error connecting to disque: ${err}`);
  });

  setTimeout(
    () => {
      if (connected === false) {
        logger.error(`Never connected to disqueue`);
      }
    },
    3000
  );
}
```

**Comment by gideonairex** [comment]
<img width="1420" alt="screen shot 2016-02-10 at 1 47 58 pm" src="https://cloud.githubusercontent.com/assets/6386061/12939668/eef25380-cffc-11e5-83dd-cc82e34a56c0.png">

Ive tested your code and it seems fine. I changed the disque server to a non existing port. If you look at bottom right. It throws the error `Error connecting to disque: Error: Connection timeout`

**Environment**
node version is `4.2.4`
disqueue-node `1.1.1`

**Comment by swarajban** [comment]
Hey, so weird! I am seeing the error event emitted now. Not sure what was happening earlier, closing this
