### ISSUE TITLE
Show job returns response as an an array, not an object with keys and values

### ISSUE THREAD

**Issue by swarajban** [gideonairex/disqueue-node#5]
When I call disqueue.show(<jobID>), the result is a 'raw' array where each odd-indexed element is a key, and each even-indexed element is the value. (I am not sure if the other commands return data in a similar format). It would be useful if disqueue-node automatically turned the raw, array response into an object hash that could be used easily

Current response:

```
result = [
 'id'
 'D-0ca28763-t8Tl5YL/P5+9vaJ6utmv7/e8-05a1',
 'queue',
 'my-disqueue',
 'state',
 'queued',
 ...
]
```

What I think it should be:

```
result: {
 id: ''D-0ca28763-t8Tl5YL/P5+9vaJ6utmv7/e8-05a1',
 queue: 'my-disqueue',
 state: 'queued',
 ...
}
```

**Comment by swarajban** [comment]
Wrote this for myself, seems to work OK, but not sure where all it would need to be incorporated in your library though:

```
// Transforms ['id', '1234', 'queue', 'my-queue', ...] => {'id': '1234', 'queue': 'my-queue', ...}
export function parseDisqueueResult (result) {
  const parsedResult = {};
  for (let i = 0; i < result.length; i += 2) {
    const key = result[i];
    const value = result[i+1];
    parsedResult[key] = value;
  }
  return parsedResult;
}
```

**Comment by gideonairex** [comment]
@swarajban Thanks I can apply this. I was thinking before that it would just return raw results. Now Im thinking that I should decorate the results. Will add decorators for this.

**Comment by gideonairex** [comment]
@swarajban I have merged the code and its available in disqueue-node 1.1.0 [ fix ](https://github.com/gideonairex/disqueue-node/commit/91ae4bf638beca1be7fecc7d5ea79ff3b09b19e7)

**Comment by swarajban** [comment]
Awesome, thanks. I'll check it out tomorrow

**Comment by gideonairex** [comment]
@swarajban is this good ? can we close this?

**Comment by swarajban** [comment]
Hi @gideonairex, sorry for the delay. Just upgraded to 1.2.0, and it works great!

You may have broken some people's applications, however, since `show`'s response is now an object. Not sure how many people are using this though. Happy to close this now

**Comment by gideonairex** [comment]
Yeah i should have turned it to version 2.
